---
#
# Webserver / Icinga Web 2
#
# Enable HTTPS
# Certificates and keys must of course exist and
# also have the correct file permissions
#apache::default_ssl_vhost: true
#apache::default_ssl_cert: <path>/apache.crt
#apache::default_ssl_key: <path>/apache.key

# Optional for certificate validation you can use 
#apache::default_ssl_ca: <path>/ca.crt
# or a CA chain
#apache::default_ssl_chain: <path>/certificates.crt

# Disable HTTP
#apache::default_vhost: false

#
# PostgreSQL
#

