---
version: 5
defaults:
  datadir: icinga.hiera
  data_hash: yaml_data
hierarchy:
  - name: "Custom user answers"
    path: "custom.yaml"
  - name: "Kafo Answers"
    path: "%{facts.kafo.scenario.answer_file}"
  - name: "Built in"
    paths:
      - "scenario/%{facts.kafo.scenario.id}/family/%{facts.os.family}-%{facts.os.release.major}.yaml"
      - "family/%{facts.os.family}-%{facts.os.release.major}.yaml"
      - "family/%{facts.os.family}.yaml"
      - "common.yaml"
