---
:name: Server-IDO-MySQL
:description: 'Install Icinga incl. Web GUI and  and configure it as a server with a MySQL database as IDO backend'
:answer_file: "./config/server-ido-mysql-answers.yaml"
:color_of_background: :dark
:colors: true
:custom: {}
:enabled: true
:facts: {}
:hiera_config: "./config/icinga-hiera.yaml"
:hook_dirs: []
:ignore_undocumented: true
:installer_dir: "."
:log_dir: "./_build/"
:log_level: debug
:log_name: server-ido-mysql.log
:low_priority_modules:
- web
- feature
- server
- plugins
- install
:mapping: {}
:module_dirs: "./_build/modules/"
:no_prefix: false
:order:
- install
- install::plugins
- install::server
- icinga2::feature::graphite
- icinga2::feature::influxdb
- icinga2::feature::livestatus
- icinga2::feature::gelf
- icinga2::feature::elasticsearch
- install::web
:parser_cache_path: "./_build/parser_cache/server-ido-mysql.yaml"
:skip_puppet_version_check: false
:store_dir: ''
:verbose: true
:verbose_log_level: notice
