---
install::repos: true
install::server: true
install::web:
  manage_backend: true
  backend_db_type: pgsql
  create_backend_database: true
  manage_frontend: true
  db_type: pgsql
  create_database: true
  enable_director: true
  director_db_type: pgsql
  create_director_database: true
  enable_business_process: true
install::features: true
