---
install::repos: true
install::server: true
install::icingadb: false
install::features: true
install::web:
  icingaweb: true
  db_type: mysql
  create_database: true
  ido: true
  ido_db_type: mysql
  ido_create_database: true
  director: true
  director_db_type: mysql
  director_create_database: true
