---
install::repos: true
install::server: true
install::icingadb:
  icingadb: true
  db_type: pgsql
  create_database: true 
install::features: true
install::web:
  icingaweb: true
  db_type: pgsql
  create_database: true
  ido_db_type: pgsql
  ido_create_database: true
  director: true
  director_db_type: pgsql
  director_create_database: true
