---
install::repos: true
install::server: true
install::web:
  manage_backend: true
  backend_db_type: pgsql
  create_backend_database: true
  manage_frontend: true
  db_type: pgsql
  create_database: true
  business_processes: true
install::feature::elasticsearch: false
install::feature::gelf: false
install::feature::graphite: false
install::feature::influxdb: false
install::feature::livestatus: false
