---
:name: Server-IDO-MySQL
:description: 'Install Icinga incl. Web GUI and  and configure it as a server with a MySQL database as IDO backend'
:answer_file: "./config/server-ido-mysql-answers.yaml"
:color_of_background: :dark
:colors: true
:custom: {}
:enabled: true
:facts: {}
:hiera_config: "./config/icinga-hiera.yaml"
:hook_dirs: []
:ignore_undocumented: true
:installer_dir: "."
:log_dir: "./_build/"
:log_level: debug
:log_name: server-ido-mysql.log
:low_priority_modules:
- feature
- web
- server
- repos
:mapping:
  :install::repos:
    :dir_name: install
    :manifest_name: repos
    :params_name: params
  :install::server:
    :dir_name: install
    :manifest_name: server
    :params_name: params
:module_dirs: "./_build/modules/"
:no_prefix: false
:order:
- install::repos
- install::server
- install::web
- install::feature::elasticsearch
- install::feature::gelf
- install::feature::graphite
- install::feature::influxdb
- install::feature::livestatus
:parser_cache_path: "./_build/parser_cache/server-ido-mysql.yaml"
:skip_puppet_version_check: false
:store_dir: ''
:verbose: true
:verbose_log_level: notice
