---
install::repos: true
install::server: true
install::web:
  manage_backend: true
  backend_db_type: mysql
  create_backend_database: true
  manage_frontend: true
  db_type: mysql
  create_database: true
  business_processes: true
