---
:answer_file: ./config/standalone-answers.yaml
:color_of_background: :dark
:colors: true
:custom: {}
:description: ''
:enabled: true
:facts: {}
:hiera_config: ./config/icinga-hiera.yaml
:hook_dirs: []
:ignore_undocumented: true
:installer_dir: .
:log_dir: ./_build/
:log_level: debug
:log_name: standalone.log
:low_priority_modules:
- icinga::repos
- install
- install::server
- install::web
:mapping: {}
:module_dirs: ./_build/modules/
:name: Standalone
:no_prefix: false
:order:
- icinga::repos
- install::server
- install
- install::web
:parser_cache_path: ./_build/parser_cache/standalone.yaml
:skip_puppet_version_check: false
:store_dir: ''
:verbose: true
:verbose_log_level: notice
