---
:name: Worker
:description: 'Install Icinga and configure it as a worker aka satellite'
:enabled: true
:log_dir: "./_build/"
:store_dir: ''
:log_name: worker.log
:log_level: debug
:no_prefix: false
:mapping: {}
:answer_file: "./config/worker-answers.yaml"
:installer_dir: "."
:module_dirs: "./_build/modules/"
:colors: true
:color_of_background: :dark
:hook_dirs: []
:custom: {}
:facts: {}
:low_priority_modules:
- worker
- plugins
- install
:verbose: true
:verbose_log_level: notice
:skip_puppet_version_check: false
:parser_cache_path: "./_build/parser_cache/worker.yaml"
:ignore_undocumented: true
:order:
- install
- install::plugins
- install::worker
:hiera_config: "./config/icinga-hiera.yaml"
